// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RenovatorApp.Infrastructure.Data;

#nullable disable

namespace RenovatorApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RenovatorAppDbContext))]
    [Migration("20260610211841_AddCalendarEvents")]
    partial class AddCalendarEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomerProperty", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.HasKey("CustomerId", "PropertyId");

                    b.HasIndex("PropertyId");

                    b.ToTable("CustomerProperty", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountrySubDivisionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AddressId");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.AppSetting", b =>
                {
                    b.Property<Guid>("AppSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppSettingId");

                    b.HasIndex("RenoCompanyID", "Name")
                        .IsUnique();

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Building", b =>
                {
                    b.Property<Guid>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("BuildingId");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.BuildingType", b =>
                {
                    b.Property<Guid>("BuildingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.HasKey("BuildingTypeId");

                    b.HasIndex("RenoCompanyID", "Name")
                        .IsUnique();

                    b.ToTable("BuildingType", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.CalendarEvent", b =>
                {
                    b.Property<Guid>("CalendarEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllDay")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<string>("EventAlertTimes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InspectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RenoUserID")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CalendarEventId");

                    b.HasIndex("Date");

                    b.HasIndex("InspectionId");

                    b.HasIndex("RenoCompanyID");

                    b.HasIndex("RenoUserID");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CalendarEvent", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AlternatePhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("BalanceWithJobs")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid?>("BillAddressId")
                        .HasColumnType("uuid");

                    b.Property<bool>("BillWithParent")
                        .HasColumnType("boolean");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyRefName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrencyRefValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullyQualifiedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Job")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentRefName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentRefValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethodRefName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethodRefValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredDeliveryMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryEmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrintOnCheckName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("QuickBooksCreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuickBooksCustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("QuickBooksLastUpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<string>("SalesTermRefName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SalesTermRefValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ShipAddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyncToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Taxable")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.HasIndex("BillAddressId");

                    b.HasIndex("CompanyName");

                    b.HasIndex("DisplayName");

                    b.HasIndex("FamilyName");

                    b.HasIndex("RenoCompanyID");

                    b.HasIndex("ShipAddressId");

                    b.HasIndex("RenoCompanyID", "QuickBooksCustomerId")
                        .IsUnique()
                        .HasFilter("\"QuickBooksCustomerId\" <> ''");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Document", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InspectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentId");

                    b.HasIndex("CreateDate");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("InspectionId");

                    b.HasIndex("RenoCompanyID");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.DocumentType", b =>
                {
                    b.Property<Guid>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DocumentTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DocumentType", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<decimal>("BillRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("BillableTime")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("HiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HourlyCostRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PrimaryAddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrimaryEmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrintOnCheckName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("QuickBooksCreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QuickBooksEmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("QuickBooksLastUpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReleasedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyncToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DisplayName");

                    b.HasIndex("FamilyName");

                    b.HasIndex("PrimaryAddressId");

                    b.HasIndex("RenoCompanyID");

                    b.HasIndex("RenoCompanyID", "QuickBooksEmployeeId")
                        .IsUnique();

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Inspection", b =>
                {
                    b.Property<Guid>("InspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("GeneralNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InspectionId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InspectionDate");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RenoCompanyID");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("Inspection", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionArea", b =>
                {
                    b.Property<Guid>("InspectionAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OverallRating")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("InspectionAreaId");

                    b.HasIndex("AreaTypeId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("PropertyId");

                    b.ToTable("InspectionArea", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionAreaCategory", b =>
                {
                    b.Property<Guid>("InspectionAreaCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("InspectionAreaCategoryId");

                    b.HasIndex("RenoCompanyID", "Name")
                        .IsUnique();

                    b.ToTable("InspectionAreaCategory", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionAreaNote", b =>
                {
                    b.Property<Guid>("InspectionAreaNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InspectionAreaNoteId");

                    b.HasIndex("AreaId");

                    b.ToTable("InspectionAreaNote", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionAreaNoteEstimateItem", b =>
                {
                    b.Property<Guid>("InspectionAreaNoteEstimateItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaNoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Hours")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InspectionAreaNoteEstimateItemId");

                    b.HasIndex("AreaNoteId");

                    b.ToTable("InspectionAreaNoteEstimateItem", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionAreaNotePhoto", b =>
                {
                    b.Property<Guid>("InspectionAreaNotePhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaNoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.HasKey("InspectionAreaNotePhotoId");

                    b.HasIndex("AreaNoteId");

                    b.ToTable("InspectionAreaNotePhoto", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionAreaType", b =>
                {
                    b.Property<Guid>("InspectionAreaTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("InspectionAreaTypeId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RenoCompanyID", "Name")
                        .IsUnique();

                    b.ToTable("InspectionAreaType", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Inspector", b =>
                {
                    b.Property<Guid>("InspectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.HasKey("InspectorId");

                    b.ToTable("Inspectors", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.MileageTracking", b =>
                {
                    b.Property<Guid>("MileageTrackingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EndingLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndingPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InspectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<string>("StartingLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartingPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalMileage")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("TotalTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("TrackingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MileageTrackingID");

                    b.HasIndex("InspectionId");

                    b.HasIndex("RenoCompanyID");

                    b.HasIndex("TrackingStartedAtUtc");

                    b.ToTable("MileageTracking", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.MileageTrackingWaypoint", b =>
                {
                    b.Property<Guid>("MileageTrackingWaypointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CumulativeMiles")
                        .HasColumnType("double precision");

                    b.Property<string>("GpsCoordinates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<Guid>("MileageTrackingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("WaypointTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MileageTrackingWaypointId");

                    b.HasIndex("MileageTrackingId");

                    b.HasIndex("WaypointTime");

                    b.ToTable("MileageTrackingWaypoint", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Part", b =>
                {
                    b.Property<Guid>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPackage")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PackageUnits")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartSourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartId");

                    b.HasIndex("Name");

                    b.HasIndex("PartSourceId");

                    b.HasIndex("RenoCompanyID");

                    b.ToTable("Part", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.PartSource", b =>
                {
                    b.Property<Guid>("PartSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.HasKey("PartSourceId");

                    b.HasIndex("RenoCompanyID", "Name")
                        .IsUnique();

                    b.ToTable("PartSource", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Property", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.HasKey("PropertyId");

                    b.ToTable("Property", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.RenoCompany", b =>
                {
                    b.Property<Guid>("RenoCompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RenoCompanyID");

                    b.HasIndex("Name");

                    b.ToTable("RenoCompany", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.RenoUser", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhonePrimary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneSecondary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RenoCompanyID")
                        .HasColumnType("uuid");

                    b.HasKey("UserID");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RenoCompanyID");

                    b.ToTable("RenoUser", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Role", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uuid");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("CustomerProperty", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RenovatorApp.Infrastructure.Models.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Address", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.Property", "Property")
                        .WithOne("Address")
                        .HasForeignKey("RenovatorApp.Infrastructure.Models.Address", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Building", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.BuildingType", "BuildingType")
                        .WithMany("Buildings")
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RenovatorApp.Infrastructure.Models.Property", "Property")
                        .WithMany("Buildings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingType");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.CalendarEvent", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.Inspection", "Inspection")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RenovatorApp.Infrastructure.Models.RenoUser", "RenoUser")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("RenoUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inspection");

                    b.Navigation("RenoUser");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Customer", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.Address", "BillAddress")
                        .WithMany("BillingCustomers")
                        .HasForeignKey("BillAddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RenovatorApp.Infrastructure.Models.Address", "ShipAddress")
                        .WithMany("ShippingCustomers")
                        .HasForeignKey("ShipAddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BillAddress");

                    b.Navigation("ShipAddress");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Document", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.Customer", "Customer")
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RenovatorApp.Infrastructure.Models.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RenovatorApp.Infrastructure.Models.Inspection", "Inspection")
                        .WithMany("Documents")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("DocumentType");

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Employee", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.Address", "PrimaryAddress")
                        .WithMany("Employees")
                        .HasForeignKey("PrimaryAddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrimaryAddress");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Inspection", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.Customer", "Customer")
                        .WithMany("Inspections")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RenovatorApp.Infrastructure.Models.Property", "Property")
                        .WithMany("Inspections")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionArea", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.InspectionAreaType", "AreaType")
                        .WithMany("Areas")
                        .HasForeignKey("AreaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RenovatorApp.Infrastructure.Models.Building", "Building")
                        .WithMany("Areas")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RenovatorApp.Infrastructure.Models.Property", "Property")
                        .WithMany("Areas")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaType");

                    b.Navigation("Building");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionAreaNote", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.InspectionArea", "Area")
                        .WithMany("AreaNotes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionAreaNoteEstimateItem", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.InspectionAreaNote", "AreaNote")
                        .WithMany("EstimateItems")
                        .HasForeignKey("AreaNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaNote");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionAreaNotePhoto", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.InspectionAreaNote", "AreaNote")
                        .WithMany("Photos")
                        .HasForeignKey("AreaNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaNote");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionAreaType", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.InspectionAreaCategory", "Category")
                        .WithMany("AreaTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.MileageTracking", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.Inspection", "Inspection")
                        .WithMany("MileageTrackingRecords")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.MileageTrackingWaypoint", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.MileageTracking", "MileageTracking")
                        .WithMany("Waypoints")
                        .HasForeignKey("MileageTrackingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MileageTracking");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Part", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.PartSource", "PartSource")
                        .WithMany("Parts")
                        .HasForeignKey("PartSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartSource");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.RenoUser", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.RenoCompany", "RenoCompany")
                        .WithMany("Users")
                        .HasForeignKey("RenoCompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RenoCompany");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.UserRole", b =>
                {
                    b.HasOne("RenovatorApp.Infrastructure.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RenovatorApp.Infrastructure.Models.RenoUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Address", b =>
                {
                    b.Navigation("BillingCustomers");

                    b.Navigation("Employees");

                    b.Navigation("ShippingCustomers");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Building", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.BuildingType", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Customer", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Inspections");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Inspection", b =>
                {
                    b.Navigation("CalendarEvents");

                    b.Navigation("Documents");

                    b.Navigation("MileageTrackingRecords");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionArea", b =>
                {
                    b.Navigation("AreaNotes");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionAreaCategory", b =>
                {
                    b.Navigation("AreaTypes");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionAreaNote", b =>
                {
                    b.Navigation("EstimateItems");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.InspectionAreaType", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.MileageTracking", b =>
                {
                    b.Navigation("Waypoints");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.PartSource", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Property", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Areas");

                    b.Navigation("Buildings");

                    b.Navigation("Inspections");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.RenoCompany", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.RenoUser", b =>
                {
                    b.Navigation("CalendarEvents");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RenovatorApp.Infrastructure.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
