// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RenovatorApp.Infrastructure.Data;

#nullable disable

namespace RenovatorApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RenovatorAppDbContext))]
    [Migration("20260518054500_AddQuickBooksEmployees")]
    partial class AddQuickBooksEmployees
    {
    }
}
